//
//  CartListRouter.swift
//  ST Ecommerce
//
//  Created Hive Innovation Dev on 8/29/22.
//  Copyright © 2022 Shashi. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import UIKit
import Foundation

class CartListRouter: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "CartList", bundle: nil)
    
    // MARK: Module Setup
    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: CartListViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = CartListInteractor()
        let presenter = CartListPresenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension CartListRouter: CartListPresenterToRouterProtocol {
    
    func navigate(to option: CartListNavigationOption) {
        // ...
    }
    
}
