//
//  CartListPresenter.swift
//  ST Ecommerce
//
//  Created Hive Innovation Dev on 8/29/22.
//  Copyright © 2022 Shashi. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class CartListPresenter {
    
    // MARK: - Private properties
    private unowned var view: CartListPresenterToViewProtocl
    private var interactor: CartListPresentorToInterectorProtocol
    private var router: CartListPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: CartListPresenterToViewProtocl, interactor: CartListPresentorToInterectorProtocol, router: CartListPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension CartListPresenter: CartListViewToPresenterProtocol {
    
    func started() {
        view.initialControlSetup()
    }
    
}

// MARK: - Interactor to Presenter
extension CartListPresenter: CartListInterectorToPresenterProtocol {
    
}

