//
//  CartListEntity.swift
//  ST Ecommerce
//
//  Created Hive Innovation Dev on 8/29/22.
//  Copyright © 2022 Shashi. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
